version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://aspex1_user:qwerty@db/aspex1_db

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=aspex1_user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=aspex1_db
