"""remove is_booked from Table

Revision ID: 808fd82e9b34
Revises: a457344035de
Create Date: 2023-06-01 04:10:11.642323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808fd82e9b34'
down_revision = 'a457344035de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_booked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
