"""add default val for capacity in Table

Revision ID: bfa5668dfdbf
Revises: c7792e92b470
Create Date: 2023-06-01 18:35:33.231831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa5668dfdbf'
down_revision = 'c7792e92b470'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE tables SET capacity = 2 WHERE capacity < 2;")
    op.execute("ALTER TABLE tables ADD CONSTRAINT min_table_capacity CHECK (capacity >= 2);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tables DROP CONSTRAINT min_table_capacity;")
    # ### end Alembic commands ###
