"""is_active field added to Booking and Table

Revision ID: c7792e92b470
Revises: 808fd82e9b34
Create Date: 2023-06-01 17:24:16.382844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7792e92b470'
down_revision = '808fd82e9b34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    op.add_column('tables', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_active')
    op.drop_column('bookings', 'is_active')
    # ### end Alembic commands ###
