"""Initial migration

Revision ID: e27b334e53a9
Revises: a79ab39bc0d4
Create Date: 2023-06-01 00:14:20.911231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27b334e53a9'
down_revision = 'a79ab39bc0d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
